"use client";

import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const formatter = new Intl.NumberFormat("ar-SA", { maximumFractionDigits: 1 });
function TooltipArabic({ active, payload, label }: { active?: boolean; payload?: Array<{ name?: string; value?: number | null; color?: string }>; label?: string }) { if (!active || !payload?.length) return null; return <div className="chart-tooltip"><strong>{label}</strong>{payload.map((item) => <span key={item.name} style={{ color: item.color }}>{item.name}: {item.value === null || item.value === undefined ? "—" : formatter.format(item.value)}٪</span>)}</div>; }

export function ReportsOverviewCharts({ trend, categories }: { trend: Array<{ label: string; impact: number | null; workshopCount: number }>; categories: Array<{ name: string; impact: number | null }> }) {
  return <div className="overview-charts"><section className="report-visual-card"><div className="report-section-heading"><div><h2>اتجاه الأثر عبر الزمن</h2><p>متوسط التحسن المسجل في التقارير المكتملة.</p></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={280}><LineChart data={trend} margin={{ top: 8, right: 8, left: 0, bottom: 8 }}><CartesianGrid strokeDasharray="3 3" stroke="#24332c" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#9caea4", fontSize: 10 }} /><YAxis tickFormatter={(value) => `${value}%`} tick={{ fill: "#9caea4", fontSize: 10 }} /><Tooltip content={<TooltipArabic />} /><Line name="متوسط الأثر" type="monotone" dataKey="impact" stroke="#26b879" strokeWidth={2.5} dot={{ fill: "#26b879", r: 3 }} /></LineChart></ResponsiveContainer></div></section><section className="report-visual-card"><div className="report-section-heading"><div><h2>أفضل المجالات</h2><p>حسب متوسط مؤشر الأثر في التقارير المتاحة.</p></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={280}><BarChart data={categories} layout="vertical" margin={{ top: 8, right: 18, left: 12, bottom: 8 }}><CartesianGrid strokeDasharray="3 3" stroke="#24332c" horizontal={false} /><XAxis type="number" tickFormatter={(value) => `${value}%`} tick={{ fill: "#9caea4", fontSize: 10 }} /><YAxis type="category" dataKey="name" width={100} tick={{ fill: "#9caea4", fontSize: 10 }} /><Tooltip content={<TooltipArabic />} /><Bar name="متوسط الأثر" dataKey="impact" fill="#4a78d1" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div></section></div>;
}
