import Link from "next/link";
import { resolveImpactBand, type ReportComparisonRow } from "@/src/lib/reporting";
import { StatusBadge } from "@/src/components/ui/status-badge";

const formatter = new Intl.NumberFormat("ar-SA", { maximumFractionDigits: 1 });
function value(value: number | null, suffix = "") { return value === null ? "—" : `${formatter.format(value)}${suffix}`; }

export function ReportComparison({ rows, selectedIds, filterParams }: { rows: ReportComparisonRow[]; selectedIds: string[]; filterParams: Record<string, string | undefined> }) {
  const hidden = Object.entries(filterParams).filter(([, item]) => item).map(([key, item]) => <input key={key} type="hidden" name={key} value={item} />);
  return <section className="report-panel report-comparison-panel"><div className="report-section-heading"><div><h2>مقارنة الورش</h2><p>اختر من ورشتين إلى خمس ورش لمقارنة الأثر، القبلي/البعدي، استجابة المشاركين، والمجال.</p></div></div><form method="get" className="comparison-form">{hidden}<div className="comparison-selection">{rows.length === 0 ? <span className="muted-note">لا توجد تقارير قابلة للمقارنة ضمن الفلاتر الحالية.</span> : rows.map((row) => <label key={row.reportId} className="comparison-option"><input type="checkbox" name="compare" value={row.reportId} defaultChecked={selectedIds.includes(row.reportId)} /> <span><strong>{row.title}</strong><small>{row.category} · {row.participantCount.toLocaleString("ar-SA")} مشارك</small></span></label>)}</div><button className="button button-secondary" type="submit" disabled={rows.length === 0}>تحديث المقارنة</button></form>{selectedIds.length > 0 && selectedIds.length < 2 && <p className="comparison-hint" role="status">اختر ورشة أخرى على الأقل لإظهار المقارنة.</p>}{selectedIds.length >= 2 && <div className="report-table-wrap"><table className="report-table comparison-table"><thead><tr><th>الورشة</th><th>المجال</th><th>القبلي</th><th>البعدي</th><th>الأثر</th><th>تقييم المشاركين</th><th>الاستجابة</th></tr></thead><tbody>{rows.filter((row) => selectedIds.includes(row.reportId)).map((row) => { const band = resolveImpactBand(row.impact); return <tr key={row.reportId}><td><Link className="table-link" href={`/dashboard/workshops/${row.workshopId}/report`}>{row.title}</Link></td><td>{row.category}</td><td>{value(row.pre)}</td><td>{value(row.post)}</td><td>{band ? <StatusBadge tone={band.tone}>{value(row.impact, "٪")} · {band.label}</StatusBadge> : "—"}</td><td>{value(row.teacherAverage)} / 5</td><td>{value(row.responseRate, "٪")}</td></tr>; })}</tbody></table></div>}</section>;
}
