import { ArrowLeft, LockKeyhole, Settings2, UsersRound } from "lucide-react";
import Link from "next/link";
import { PageHeader } from "@/src/components/ui/page-header";
import { Stepper } from "@/src/components/ui/stepper";
import { LockedState } from "@/src/components/ui/locked-state";
import { SchoolSettingsForm } from "@/src/components/settings/school-settings-form";
import { requireDashboardContext } from "@/src/lib/dashboard-access";
import { Permission } from "@/src/lib/permissions";
import { db } from "@/src/lib/db";

const dateFormatter = new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium", timeStyle: "short" });
const labels: Record<string, string> = { SCHOOL_CREATED: "إنشاء المدرسة", SCHOOL_UPDATED: "تغيير بيانات المدرسة", STAFF_IMPORT_COMMITTED: "استيراد المنسوبين", STAFF_REIMPORT_COMMITTED: "إعادة استيراد المنسوبين", STAFF_MANUALLY_UPDATED: "تصحيح بيانات منسوب", STAFF_PHONE_CORRECTED: "تصحيح رقم جوال", STAFF_IDENTITY_CORRECTED: "تصحيح رقم هوية", WORKSHOP_CREATED: "إنشاء ورشة", WORKSHOP_FINALIZED: "اعتماد ورشة", REPORT_GENERATED: "إصدار تقرير", REPORT_EXPORTED: "تصدير تقرير" };

export default async function SettingsPage() {
  const session = await requireDashboardContext({ allowSetup: true, permission: Permission.SchoolSettingsManage });
  const audits = await db.auditLog.findMany({ where: { schoolId: session.membership!.schoolId }, orderBy: { createdAt: "desc" }, take: 12, select: { id: true, action: true, createdAt: true, entity: true } });
  return <><PageHeader eyebrow="إدارة المنصة" title="الإعدادات" description="إعدادات المدرسة ومعايير القياس والأوزان الافتراضية." action={<div className="page-header-actions"><Link className="button button-secondary" href="/dashboard/settings/activity"><ArrowLeft size={15} /> النشاط والتدقيق</Link><Link className="button button-secondary" href="/dashboard/settings/team"><UsersRound size={15} /> فريق المدرسة</Link></div>} /><section className="panel"><div className="panel-header"><div><h2 className="panel-title">بيانات المدرسة</h2><p className="panel-caption">تُسجل كل تعديلات بيانات المدرسة في سجل التدقيق.</p></div><Settings2 size={18} color="var(--emerald)" /></div><SchoolSettingsForm school={{ name: session.membership!.school.name, educationAdministration: session.membership!.school.educationAdministration, educationOffice: session.membership!.school.educationOffice, region: session.membership!.school.region, city: session.membership!.school.city, principalName: session.membership!.school.principalName }} /></section><section className="panel settings-panel"><div className="panel-header"><div><h2 className="panel-title">إعداد ورشة جديدة</h2><p className="panel-caption">خطوات واضحة قبل اعتماد أي قياس.</p></div><Settings2 size={18} color="var(--emerald)" /></div><Stepper steps={["المعلومات", "المشاركون", "المعايير", "القياس القبلي"]} current={0} /><div className="settings-placeholder"><LockKeyhole size={18} /><div><strong>إعدادات المعايير</strong><p>يمكن إدارة القوالب والمعايير من مسار إنشاء الورشة.</p></div></div><LockedState title="إعدادات متقدمة قيد التجهيز" description="لا تُجرى تغييرات حساسة دون صلاحية مالك المدرسة." /></section><section className="panel audit-panel" id="audit"><div className="panel-header"><div><h2 className="panel-title">آخر نشاط</h2><p className="panel-caption">للسجل الكامل استخدم صفحة النشاط والتدقيق.</p></div><Link className="text-link" href="/dashboard/settings/activity">عرض السجل الكامل</Link></div>{audits.length === 0 ? <div className="detail-empty">لا يوجد نشاط مسجل بعد.</div> : <div className="activity-list">{audits.map((audit) => <div className="activity-item" key={audit.id}><span className="activity-dot" /><span><strong>{labels[audit.action] ?? audit.action}</strong><small>{audit.entity} · {dateFormatter.format(audit.createdAt)}</small></span></div>)}</div>}</section></>;
}
