import type { Metadata } from "next";
import { ArrowLeft, BarChart3, CheckCircle2, ClipboardCheck, FileSpreadsheet, FileText, Gauge, GraduationCap, LayoutDashboard, LockKeyhole, MessageSquareText, School, ShieldCheck, Sparkles, Target, Users, Workflow, X } from "lucide-react";
import Link from "next/link";
import { Logo } from "@/src/components/brand/logo";
import { LandingNavbar } from "@/src/components/landing/landing-navbar";
import { LaunchAvailability } from "@/src/components/landing/launch-availability";
import { StickyCta } from "@/src/components/landing/sticky-cta";
import { LANDING_CONFIG } from "@/src/config/landing";
import { getLaunchAvailability } from "@/src/lib/license-service";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "أثر | قياس أثر البرامج والورش في مدرستك",
  description: "منصة أثر تساعد المدارس على قياس أثر الورش والبرامج التدريبية، وإدارة المنسوبين، واتخاذ قرارات أوضح من البيانات.",
  openGraph: { title: "أثر | من البيانات إلى القرار", description: "قياس أثر التدريب في المدارس بصورة أبسط وأوضح.", type: "website" },
};

const workflow = [
  ["01", "أنشئ حسابك", "ابدأ بحساب مدير المدرسة وأكمل بيانات مدرستك."], ["02", "استورد المنسوبين", "ارفع ملف المنسوبين الرسمي، وراجع أي سجلات تحتاج توضيحًا."], ["03", "أنشئ ورشة أو خطة", "ابدأ من الصفر أو استخدم قالبًا وخطط للنمو المهني."], ["04", "اختر المشاركين", "حدد المنسوبين والمدرب أو المنفذ من سجلك المدرسي."], ["05", "حدد معايير الأثر", "ابنِ المعايير والأوزان، أو ابدأ من قوالب محفوظة."], ["06", "نفذ القياس القبلي", "قيّم مستوى المشاركين قبل بدء الورشة بصورة منظمة."], ["07", "اجمع التقييمات", "يقيّم المعلمون الورشة خلال فترة التنفيذ من بوابة بسيطة."], ["08", "اقرأ التقرير", "اعتمد القياس البعدي واستخرج تقريرًا ثابتًا قابلًا للطباعة والتصدير."],
];

const features = [
  [Users, "إدارة المنسوبين", "استيراد القوائم، مراجعة التعارضات، وإدارة السجل دون فقد تاريخ المشاركات."], [Workflow, "قياس الورش", "معالج واضح للمعلومات والمشاركين والمعايير والقبلي والاعتماد."], [ClipboardCheck, "قبلي وبعدي", "قياس مركزي يحسب الفروقات والتحسن والأوزان بصورة قابلة للتفسير."], [GraduationCap, "بوابة المعلمين", "وصول بسيط للمعلم المرتبط بالورشة وتقييم مرة واحدة خلال الفترة المتاحة."], [BarChart3, "تحليلات عملية", "مؤشرات وتوزيعات ومقارنات تساعد المدير على رؤية ما يحتاج متابعة."], [FileText, "تقارير رسمية", "تقرير Snapshot ثابت، مع طباعة وPDF وExcel دون بيانات سرية غير لازمة."], [School, "خطط النمو المهني", "اجمع البرامج التدريبية في خطة واحدة وتابع جاهزية كل برنامج."], [FileSpreadsheet, "استيراد منظم", "تحليل ملفات نور ومراجعة السجلات قبل الحفظ، مع دعم إعادة الاستيراد."], [ShieldCheck, "عزل وصلاحيات", "كل مدرسة ترى بياناتها فقط، مع صلاحيات مركزية وسجل تدقيق."], [LayoutDashboard, "لوحة واضحة", "إجراءات تحتاج انتباهك، ورش، مؤشرات، ومسودات في مكان واحد."],
];

const faqs = [
  ["لمن صممت منصة أثر؟", "صممت لمديري المدارس والفرق التعليمية التي تريد متابعة أثر الورش والبرامج التدريبية بطريقة منظمة ومفهومة."], ["هل أحتاج نظامًا آخر لتشغيلها؟", "لا. تبدأ من حساب المدير، وتدعم استيراد قائمة المنسوبين، ثم تدير الورش والقياسات والتقارير من داخل المنصة."], ["كيف يعمل القياس القبلي والبعدي؟", "يحدد المدير معايير الأثر وأوزانها، ثم يسجل القياس القبلي والبعدي. تعرض المنصة متوسطات وفروقات وتحسنًا على مقياس 1 إلى 5."], ["هل تقييم المعلمين جزء من مؤشر الأثر؟", "يعرض تقييم المشاركين في قسم مستقل. يمكن استخدامه في المؤشر المركب القابل للضبط، لكنه لا يستبدل نتائج القياس القبلي والبعدي."], ["ماذا يحدث بعد رفع ملف المنسوبين؟", "تحلل المنصة الملف وتعرض السجلات السليمة والتعارضات والحقول الناقصة قبل الاعتماد، حتى تتخذ قرارًا واعيًا قبل الحفظ."], ["هل يمكن تصدير التقارير؟", "نعم، للتقارير المكتملة تتوفر نسخة رسمية للطباعة وPDF وExcel، اعتمادًا على Snapshot تاريخي ثابت."], ["ما الذي يتضمنه عرض الإطلاق؟", "وصول مدى الحياة بسعر 250 ريالًا للدفع لمرة واحدة لأول 10 مشتركين. قد تتغير الأسعار لاحقًا، ويحتفظ المشتركون الأوائل بعرضهم."],
];

export default async function HomePage() {
  const availability = await getLaunchAvailability();
  const contactProps = { phone: LANDING_CONFIG.contactPhone, whatsappNumber: LANDING_CONFIG.whatsappNumber, whatsappMessage: LANDING_CONFIG.whatsappMessage };
  return <main className="landing-page">
    <LandingNavbar {...contactProps} />
    <div className="landing-shell">
      <section className="landing-hero" aria-labelledby="landing-title"><div className="landing-hero-copy"><span className="landing-eyebrow">منصة قياس الأثر التدريبي للمدارس</span><h1 id="landing-title">تميّز بأداء منسوبي مدرستك، وقِس أثر البرامج والورش بسهولة <span>مع أثر.</span></h1><p className="landing-hero-lead">من البيانات إلى القرار؛ منصة سعودية تساعدك على إدارة المنسوبين، بناء القياسات، وفهم ما يتغير بعد كل ورشة وبرنامج تدريبي.</p><span className="landing-hero-badge"><Sparkles size={15} /> قياس الأثر أصبح على بُعد نقرة واحدة منك.</span><div className="landing-actions"><Link className="button button-primary button-large" href="/auth/register">ابدأ الآن <ArrowLeft size={17} /></Link><Link className="button button-secondary button-large" href="/auth/login">دخول مدير المدرسة</Link><Link className="button button-secondary button-large" href="/teacher">دخول المعلمين</Link></div><p className="landing-action-note"><LockKeyhole size={13} /> بيانات مدرستك معزولة، والتقارير التاريخية محفوظة Snapshot.</p></div><div className="landing-hero-visual"><div className="landing-hero-panel" aria-label="معاينة بصرية للوحة أثر"><div className="landing-panel-top"><div><small>نظرة عامة</small><strong>الأثر التدريبي</strong></div><span className="landing-panel-mark"><BarChart3 size={20} /></span></div><div className="landing-panel-score"><strong>—</strong><span>بانتظار أول تقرير<br />القياس القبلي / البعدي</span></div><div className="landing-chart" aria-hidden="true"><span /><span /><span /><span /><span /><span /></div><div className="landing-panel-bottom"><div className="landing-panel-status"><small>الورش</small><strong>منظمة</strong></div><div className="landing-panel-status"><small>التقارير</small><strong>قابلة للتفسير</strong></div></div></div><p className="landing-visual-caption">معاينة بصرية من النظام — تظهر الأرقام بعد تسجيل بيانات مدرستك.</p></div></section>

      <section className="landing-section" id="about" aria-labelledby="about-title"><div className="landing-section-heading"><span className="landing-section-label">ما هي منصة أثر؟</span><h2 id="about-title">قياس أبسط، قرار أوضح.</h2><p>أثر ليست مخزنًا للبيانات فقط. هي مساحة عمل تربط قائمة المنسوبين بالورش، والقياس بالتحليل، والتقرير بالخطوة التالية.</p></div><div className="landing-about-grid"><div className="landing-copy-card"><p>بدل أن تتوزع نتائج الورش بين ملفات وجداول متفرقة، يجمع أثر دورة العمل كاملة في مكان واحد: من إنشاء الورشة واختيار المشاركين، إلى القياس القبلي والبعدي، وتقييم المشاركين، وإصدار تقرير يمكن الرجوع إليه.</p></div><div className="landing-value-card"><div className="landing-value-list"><div className="landing-value-item"><Target size={19} /><div><strong>نتيجة قابلة للفهم</strong><span>اعرض التغير لكل معيار بدل الاكتفاء بانطباع عام.</span></div></div><div className="landing-value-item"><Gauge size={19} /><div><strong>سياق يساعدك</strong><span>شاهد الجاهزية والتنبيهات وما يحتاج تدخلًا.</span></div></div><div className="landing-value-item"><ShieldCheck size={19} /><div><strong>تاريخ لا يضيع</strong><span>التقارير المكتملة مبنية على Snapshot ثابت.</span></div></div></div></div></div></section>

      <section className="landing-section" id="workflow" aria-labelledby="workflow-title"><div className="landing-section-heading"><span className="landing-section-label">كيف تعمل؟</span><h2 id="workflow-title">من أول خطوة إلى تقرير أثر واضح.</h2><p>مسار واحد مرتب، مع حالات جاهزية واضحة ومسودات محفوظة تلقائيًا عند الحاجة.</p></div><div className="landing-workflow-grid">{workflow.map(([number, title, description]) => <article className="landing-step" key={number}><span className="landing-step-number">{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>

      <section className="landing-section" id="features" aria-labelledby="features-title"><div className="landing-section-heading"><span className="landing-section-label">كل ما تحتاجه في مكان واحد</span><h2 id="features-title">أدوات مبنية حول عمل المدرسة الحقيقي.</h2><p>تستند هذه المزايا إلى دورة العمل الموجودة في المنصة، دون وعود خارج ما تستطيع المنصة تقديمه.</p></div><div className="landing-features">{features.map(([Icon, title, description]) => <article className="landing-feature" key={title as string}><span className="landing-feature-icon"><Icon size={17} /></span><h3>{title as string}</h3><p>{description as string}</p></article>)}</div></section>

      <section className="landing-section" aria-labelledby="difference-title"><div className="landing-section-heading"><span className="landing-section-label">لماذا أثر؟</span><h2 id="difference-title">انتقل من التوثيق إلى التحسين.</h2></div><div className="landing-compare"><article className="landing-compare-card"><h3>قبل أثر</h3><ul><li><X size={17} /> نتائج ورش موزعة بين ملفات ومراسلات.</li><li><X size={17} /> صعوبة معرفة ما الذي تغير فعلًا.</li><li><X size={17} /> إعادة إعداد التقرير عند كل مراجعة.</li><li><X size={17} /> متابعة يدوية للمنسوبين والتقييمات.</li></ul></article><article className="landing-compare-card is-highlight"><h3>مع أثر</h3><ul><li><CheckCircle2 size={17} /> دورة قياس واضحة من القبلي إلى البعدي.</li><li><CheckCircle2 size={17} /> مؤشرات لكل معيار مع منهجية مفهومة.</li><li><CheckCircle2 size={17} /> Snapshot وتقارير جاهزة للطباعة والتصدير.</li><li><CheckCircle2 size={17} /> تنبيهات وإجراءات مرتبة حسب الأولوية.</li></ul></article></div></section>

      <section className="landing-section" aria-labelledby="reasons-title"><div className="landing-section-heading"><span className="landing-section-label">صُممت لتوفر وقتك</span><h2 id="reasons-title">بساطة في الاستخدام، وعمق عند الحاجة.</h2></div><div className="landing-reasons"><article className="landing-reason"><h3>ابدأ تدريجيًا</h3><p>يمكنك تسجيل الحساب واستكمال المدرسة ثم استيراد المنسوبين قبل الدخول في تفاصيل الورش.</p></article><article className="landing-reason"><h3>لا تتوه في الأرقام</h3><p>تعرض لوحة المدير ما يحتاج انتباهك، بدل إغراقك بعشرات البطاقات.</p></article><article className="landing-reason"><h3>احتفظ بسياقك</h3><p>القوالب وخطط النمو المهني وإعادة الاستيراد تساعدك على العمل المتكرر بسرعة.</p></article></div></section>

      <section className="landing-section" id="pricing" aria-labelledby="pricing-title"><div className="landing-pricing"><div className="landing-pricing-copy"><span className="landing-section-label">جاهز للانطلاق؟</span><h2 id="pricing-title">ابدأ بقياس أثر أوضح اليوم.</h2><p>عرض تأسيسي محدود لمن يريد تجربة دورة العمل كاملة وبناء أساس منظم لقرارات التدريب في مدرسته.</p><div className="landing-actions"><Link className="button button-primary button-large" href="/auth/register">إنشاء حساب مدير <ArrowLeft size={17} /></Link></div></div><div className="landing-pricing-card"><LaunchAvailability totalSlots={availability.totalSlots} availableSlots={availability.availableSlots} price={availability.launchPrice} compact /></div></div></section>

      <section className="landing-section" aria-labelledby="promise-title"><div className="landing-plain-promise"><div><span className="landing-section-label">وعد أثر</span><h2 id="promise-title">لا نبيعك تعقيدًا إضافيًا.</h2><p>نرتب لك البيانات الموجودة أصلًا حتى تستطيع اتخاذ قرار تدريبي أفضل.</p></div><MessageSquareText size={39} color="var(--emerald)" aria-hidden="true" /></div></section>

      <section className="landing-section" id="faq" aria-labelledby="faq-title"><div className="landing-section-heading"><span className="landing-section-label">الأسئلة الشائعة</span><h2 id="faq-title">إجابات قبل أن تبدأ.</h2></div><div className="landing-faq">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>

      <section className="landing-final-cta" aria-labelledby="final-title"><span className="landing-section-label">أثر · من البيانات إلى القرار</span><h2 id="final-title">ابدأ من ورشة واحدة.</h2><p>ابنِ أول قياس لك، ثم دع البيانات توضح لك أين يستحق التدريب أن يستمر.</p><div className="landing-actions"><Link className="button button-primary button-large" href="/auth/register">ابدأ الآن <ArrowLeft size={17} /></Link><Link className="button button-secondary button-large" href="/auth/login">لدي حساب بالفعل</Link></div></section>
    </div>
    <footer className="landing-footer"><div className="landing-shell"><div className="landing-footer-grid"><div><Logo href="/" /><p>منصة سعودية لقياس أثر الورش والبرامج التدريبية في المدارس.</p></div><div className="landing-footer-links"><Link href="/privacy">الخصوصية</Link><Link href="/terms">الشروط</Link><Link href="/auth/login">تسجيل الدخول</Link></div></div><small>© {new Date().getFullYear()} أثر. جميع الحقوق محفوظة.</small></div></footer>
    <StickyCta {...contactProps} />
  </main>;
}
